services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - minio
    ports:
      - "8080:8080"  # Exemplo, pode remover se não quiser expor
    # environment:
    #   - DATABASE_URL=postgresql://user:pass@postgres:5432/soccer_data
    #   - MINIO_URL=http://minio:9000
    networks:
      - dev_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - dev_network


networks:
  dev_network: